/**
 * Writes resources/gemini-keys.json from the GEMINI_KEYS environment variable.
 *
 *   GEMINI_KEYS="AIza...,AIza..." node scripts/write-keys.mjs
 *
 * This exists because of a gap that is invisible until the first public release fails.
 * resources/gemini-keys.json is gitignored — it holds the real keys every installed copy
 * dictates on, and a committed key is a leaked key — so a CI checkout does not have it.
 * electron-builder lists that file under extraResources, so without this step a release
 * build either fails outright or produces an installer with no pool at all, which installs
 * perfectly and then fails on every hotkey press with "Ilova kaliti topilmadi".
 *
 * Note what does NOT solve this: setting WHISPER_UZ_BUNDLED_KEYS in the build environment.
 * That variable is read by the app at runtime, on the user's machine (src/main/keys.ts) —
 * a packaged build has no environment to inherit it from. Keys reach an installer only by
 * being in this file when electron-builder runs.
 *
 * The keys arrive through the environment rather than as an argument on purpose: an argument
 * is visible in the process table to anything else on the machine, and CI logs commands.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const TARGET = join(ROOT, 'resources', 'gemini-keys.json');

/** Same splitting rule as parseKeyList in src/main/keys.ts — a pasted list arrives with any of these. */
const keys = (process.env.GEMINI_KEYS ?? '')
  .split(/[\s,;]+/)
  .map((key) => key.trim())
  .filter(Boolean);

if (keys.length === 0) {
  // Failing loudly is the whole point. A silent empty pool here is a broken installer that
  // nobody notices until a stranger downloads it.
  console.error(
    '[keys] GEMINI_KEYS is empty — refusing to write an empty pool.\n' +
      '       In CI: add a GEMINI_KEYS repository secret (comma-separated Gemini API keys).\n' +
      '       Locally: put the keys in resources/gemini-keys.json by hand instead.'
  );
  process.exit(1);
}

/*
 * The hand-maintained copy of this file carries a `_readme`, and the generated one keeps the
 * habit: this file ships inside the installer and can be edited there to swap a spent key
 * without a rebuild, so whoever opens it next — possibly months from now, possibly not the
 * person who wrote it — should not have to go and find out what it is first.
 */
const README =
  'Gemini API keys this build dictates on. Free-tier keys with billing DISABLED only: ' +
  'this file ships inside the installer, so anyone who downloads the app can read it. ' +
  'Generated by scripts/write-keys.mjs from the GEMINI_KEYS secret — see src/main/keys.ts.';

mkdirSync(dirname(TARGET), { recursive: true });
writeFileSync(TARGET, `${JSON.stringify({ _readme: README, gemini: keys }, null, 2)}\n`);

// Count only. Never print a key — CI logs are public on a public repository.
console.log(`[keys] wrote resources/gemini-keys.json with ${keys.length} key(s)`);
